[metadata]
name = prelim
version = 0.0.1
author = BLIND_RESTORE_AUTHOR
author_email = BLIND_RESTORE_AUTHOR_EMAIL
description = PRELIM package to reproduce experiments and use method.
long_description = file: README.md
long_description_content_type = text/markdown
url = BLIND_RESTORE_PROJECT_URL
project_urls =
    Bug Tracker = BLIND_RESTORE_BUGTRACKER_URL
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    imbalanced_learn>=0.14.0
    numpy>=1.26.0
    pandas>=2.0.0
    scikit_learn>=1.5.0
    statsmodels>=0.14.0

[options.extras_require]
optional-generators =
    be-great>=0.0.14
    copulas>=0.12.0
    ctgan>=0.12.0
    ForestDiffusion>=1.0.6
    pgmpy>=1.1.0
    python-weka-wrapper3>=0.3.3
    sdv>=1.36.0
    tabgan>=3.2.0
    torch>=2.0.0
full =
    %(optional-generators)s


[options.packages.find]
where = src
